CREATE TABLE topicos(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo varchar(100) not null,
  mensagem TEXT,
  data_criacao timestamp not null,
  estado varchar(100) not null,
  autor_id bigint not null,
  curso_id bigint not null,

  constraint fk_topicos_autor_id
    foreign key(autor_id) references autores(id),

  constraint fk_topicos_curso_id
    foreign key(curso_id) references cursos(id)
);